Repository we-have-TTA/iCoder, pull requests merged in 2022-09, with the labels that each got.

#74 Questions ! add types column to questions
  app/controllers/questions_controller.rb
  app/views/questions/edit.html.erb
  app/views/questions/index.html.erb
  app/views/questions/new.html.erb
  app/views/questions/show.html.erb
  db/migrate/20220905092530_add_question_type_column_to_questions.rb
  db/schema.rb
Labels: 0.5天

#70 改寫建立container方法；新增 gem net-ssh
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/rooms_controller.rb
  app/javascript/controllers/editor_controller.js
  app/javascript/controllers/webconsole_controller.js
  app/javascript/stylesheets/rooms/room.scss
  app/javascript/stylesheets/shared/notice.scss
  app/mailers/invite_mailer.rb
  app/mailers/room_mailer.rb
  app/views/invite_mailer/say_hello_to.html.erb
  app/views/room_mailer/send_invitation_to.html.erb
  app/views/rooms/_footer.html.erb
  app/views/rooms/_room.html.erb
  app/views/rooms/_webconsole.html.erb
  app/views/rooms/index.html.erb
  app/views/rooms/invite.html.erb
  app/views/shared/_notice.html.erb
  config/email.yml
  config/environments/development.rb
  config/routes.rb
  db/migrate/20220904031846_add_uuid_to_room.rb
  db/schema.rb
Labels: Room / Live interview

#131 Action Cable - 之前研究成果加入專案，測試會不會壞掉
  Gemfile
  Gemfile.lock
  app/channels/room_channel.rb
  app/controllers/chats_controller.rb
  app/controllers/messages_controller.rb
  app/javascript/channels/room_channel.js
  app/models/message.rb
  app/views/chats/index.html.erb
  config/cable.yml
  config/routes.rb
  db/migrate/20220908074655_create_messages.rb
  db/schema.rb
Labels: T.Y負責

#127 留言功能進行，修正先前devise註冊清洗及登入跳轉路徑
  app/controllers/comments_controller.rb
  app/controllers/questions_controller.rb
  app/controllers/rooms_controller.rb
  app/controllers/teams_controller.rb
  app/controllers/users/registrations_controller.rb
  app/javascript/controllers/editor_controller.js
  app/javascript/controllers/reply_controller.js
  app/mailers/application_mailer.rb
  app/models/comment.rb
  app/models/question.rb
  app/models/user.rb
  app/views/comments/_comment.html.erb
  app/views/comments/_form.html.erb
  app/views/comments/edit.html.erb
  app/views/questions/show.html.erb
  config/routes.rb
  db/migrate/20220907144101_create_comments.rb
  db/migrate/20220909103733_add_parent_to_comments.rb
  db/schema.rb
Labels: T.Y APPD

#134 Upgrade rails version to 6.1.7
  Gemfile
  Gemfile.lock
  README.md
  app/javascript/controllers/application.js
  app/javascript/controllers/canvas_controller.js
  app/javascript/controllers/editor_controller.js
  app/javascript/controllers/index.js
  app/javascript/controllers/notice_controller.js
  app/javascript/controllers/webconsole_controller.js
  app/javascript/packs/application.js
  app/javascript/stylesheets/index.js
  app/javascript/stylesheets/tailwind.css
  pack-Dockerfile
  package-lock.json
  test/mailers/invite_mailer_test.rb
  test/mailers/previews/invite_mailer_preview.rb
Labels: T.Y APPD

#130 修正了room的樣式、新增語言選擇下拉選單、新增production模式創建container方法
  .env.example
  .rubocop.yml
  Dockerfile
  Gemfile
  app/controllers/api/v1/rooms_controller.rb
  app/controllers/application_controller.rb
  app/controllers/rooms_controller.rb
  app/controllers/teams_controller.rb
  app/javascript/controllers/editor_controller.js
  app/javascript/controllers/webconsole_controller.js
  app/javascript/stylesheets/rooms/room.scss
  app/mailers/room_mailer.rb
  app/views/rooms/_room.html.erb
  app/views/rooms/_webconsole.html.erb
  app/views/teams/index.html.erb
  config/environments/production.rb
  config/routes.rb
  docker-compose.yml
Labels: T.Y APPD

#133 Feature/add editor to question
  app/controllers/api/v1/questions_controller.rb
  app/javascript/controllers/editor_controller.js
  app/javascript/stylesheets/questions/question.scss
  app/views/questions/_form.html.erb
  app/views/questions/show.html.erb
  config/environments/production.rb
  config/routes.rb
Labels: enhancement, Question, Major, T.Y APPD

#135 Feature/canvas 先推個橡皮擦審一下🙏🙏🙏
  app/javascript/canvas/canvas.css
  app/javascript/canvas/canvas.js
  app/views/pages/canvas.html.erb
  db/schema.rb
Labels: T.Y APPD

#143 加入留言CSS、修正刪除題庫因為內部有留言出問題
  app/controllers/users/confirmations_controller.rb
  app/controllers/users/passwords_controller.rb
  app/controllers/users/sessions_controller.rb
  app/controllers/users/unlocks_controller.rb
  app/javascript/controllers/reply_controller.js
  app/javascript/stylesheets/shared/dashboard.scss
  app/javascript/stylesheets/shared/index.js
  app/models/question.rb
  app/views/comments/_comment.html.erb
  app/views/comments/_form.html.erb
  app/views/comments/edit.html.erb
  app/views/layouts/dashboard.html.erb
  app/views/questions/show.html.erb
  app/views/shared/_sidebar.html.erb
  config/application.rb
  config/routes.rb
  mailer.html.erb
Labels: T.Y APPD

#146 question room 的index 調整 外加 room搜尋
  app/controllers/questions_controller.rb
  app/controllers/rooms_controller.rb
  app/javascript/stylesheets/shared/btnstyle.scss
  app/views/questions/index.html.erb
  app/views/questions/show.html.erb
  app/views/rooms/index.html.erb
  db/schema.rb
Labels: T.Y APPD 👻

#147 引用題庫&&其餘兩種語言可以使用&&選完題庫自動連線
  app/controllers/api/v1/rooms_controller.rb
  app/javascript/controllers/editor_controller.js
  app/views/rooms/_room.html.erb
Labels: T.Y APPD 👻

#145 Set up Redis in production mode
  config/environments/production.rb
  docker-compose.yml
Labels: T.Y APPD 👻

#153 會議室內題庫優化
  app/javascript/controllers/editor_controller.js
  app/javascript/stylesheets/rooms/room.scss
  app/views/rooms/_room.html.erb
  app/views/rooms/_webconsole.html.erb
Labels: T.Y APPD 👻

#150 更改全站logo，編輯組織名、新增組織大頭貼
  app/assets/stylesheets/actiontext.scss
  app/controllers/questions_controller.rb
  app/controllers/teams_controller.rb
  app/javascript/packs/application.js
  app/javascript/stylesheets/shared/header.scss
  app/models/comment.rb
  app/models/team.rb
  app/views/active_storage/blobs/_blob.html.erb
  app/views/comments/_comment.html.erb
  app/views/comments/_form.html.erb
  app/views/questions/show.html.erb
  app/views/shared/_header.html.erb
  app/views/shared/_header_dashboard.html.erb
  app/views/shared/_header_member.html.erb
  app/views/shared/_sidebar.html.erb
  app/views/teams/edit.html.erb
  config/routes.rb
  db/migrate/20220914032030_create_active_storage_tables.active_storage.rb
  db/schema.rb
  package.json
  public/icoder_logo.png
  yarn.lock
Labels: T.Y APPD 👻

#155 Feature/pagy
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/questions_controller.rb
  app/controllers/rooms_controller.rb
  app/helpers/application_helper.rb
  app/views/questions/index.html.erb
  app/views/rooms/index.html.erb
  config/initializers/pagy.rb
Labels: T.Y APPD 👻

#157 從題庫建立房間、補上預設頭貼
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/rooms_controller.rb
  app/javascript/controllers/editor_controller.js
  app/views/questions/index.html.erb
  app/views/rooms/_room.html.erb
  app/views/shared/_sidebar.html.erb
  app/views/teams/edit.html.erb
  config/routes.rb
  db/migrate/20220915095455_add_question_belongs_to_room.rb
  db/schema.rb
  public/apple-touch-icon-precomposed.png
  public/apple-touch-icon.png
  public/default_profile.PNG
Labels: T.Y APPD 👻

#156 點擊roomtitle快速修改標題
  app/controllers/api/v1/rooms_controller.rb
  app/javascript/controllers/roomtitle_controller.js
  app/views/rooms/_footer.html.erb
  config/routes.rb
Labels: T.Y APPD 👻

#160 pagy fixed
  app/controllers/application_controller.rb
Labels: T.Y APPD 👻

#162 Question/last used 請看截圖效果
  app/controllers/api/v1/rooms_controller.rb
  app/controllers/rooms_controller.rb
  app/javascript/controllers/editor_controller.js
  app/models/room.rb
  app/views/questions/index.html.erb
  config/routes.rb
  db/migrate/20220917173030_add_last_used_column_to_question.rb
  db/schema.rb
Labels: T.Y APPD 👻

#168 首頁頁尾製作
  app/views/shared/_footer.html.erb
  public/github.png
Labels: 需要幫忙👋！！！！, T.Y APPD 👻

#173 改天芫的checkbox 為中文、 調整room內footer按鈕文字置中
  app/javascript/stylesheets/rooms/footer.scss
  app/views/rooms/index.html.erb
  config/environments/development.rb
Labels: T.Y APPD 👻

#175 pagy padding 已拉開間距 移置下方處
  app/javascript/stylesheets/shared/pagy.scss
  app/views/questions/index.html.erb
  app/views/rooms/index.html.erb
Labels: T.Y APPD 👻

#177 Feature/live result
  app/channels/room_chat_channel.rb
  app/channels/room_run_channel.rb
  app/controllers/api/v1/rooms_controller.rb
  app/controllers/rooms_controller.rb
  app/javascript/controllers/allRoom_controller.js
  app/javascript/controllers/editor_controller.js
  app/javascript/controllers/footer_controller.js
  app/javascript/controllers/runCode_controller.js
  app/javascript/controllers/webconsole_controller.js
  app/javascript/stylesheets/rooms/room.scss
  app/javascript/stylesheets/shared/pagy.scss
  app/views/orders/new.html.erb
  app/views/plans/show.html.erb
  app/views/rooms/_editor.html.erb
  app/views/rooms/_footer.html.erb
  app/views/rooms/_room.html.erb
  app/views/rooms/_select_language.html.erb
  app/views/rooms/_textchat.html.erb
  app/views/rooms/_webconsole.html.erb
  app/views/shared/_notice.html.erb
Labels: T.Y APPD 👻

#182 Revert "roomTitle按下修改後按紐CSS"
  app/javascript/controllers/roomtitle_controller.js
Labels: T.Y APPD 👻

#190 讓加入團隊頁面自動跳轉，成功加入顯示歡迎訊息
  app/channels/room_chat_channel.rb
  app/controllers/orders_controller.rb
  app/controllers/teams_controller.rb
  app/javascript/controllers/auto_controller.js
  app/javascript/controllers/participator_name_controller.js
  app/models/order.rb
  app/views/teams/join_team.html.erb
  config/routes.rb
Labels: enhancement
